# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shesonglin/Program/PublicKeyCollector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shesonglin/Program/PublicKeyCollector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shesonglin/Program/PublicKeyCollector/CMakeFiles /Users/shesonglin/Program/PublicKeyCollector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shesonglin/Program/PublicKeyCollector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SSHCollectorTestCases

# Build rule for target.
SSHCollectorTestCases: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SSHCollectorTestCases
.PHONY : SSHCollectorTestCases

# fast build rule for target.
SSHCollectorTestCases/fast:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/build
.PHONY : SSHCollectorTestCases/fast

#=============================================================================
# Target rules for targets named SSHCollector

# Build rule for target.
SSHCollector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SSHCollector
.PHONY : SSHCollector

# fast build rule for target.
SSHCollector/fast:
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/build
.PHONY : SSHCollector/fast

src/AbstractCollector.o: src/AbstractCollector.cpp.o

.PHONY : src/AbstractCollector.o

# target to build an object file
src/AbstractCollector.cpp.o:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/AbstractCollector.cpp.o
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/AbstractCollector.cpp.o
.PHONY : src/AbstractCollector.cpp.o

src/AbstractCollector.i: src/AbstractCollector.cpp.i

.PHONY : src/AbstractCollector.i

# target to preprocess a source file
src/AbstractCollector.cpp.i:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/AbstractCollector.cpp.i
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/AbstractCollector.cpp.i
.PHONY : src/AbstractCollector.cpp.i

src/AbstractCollector.s: src/AbstractCollector.cpp.s

.PHONY : src/AbstractCollector.s

# target to generate assembly for a file
src/AbstractCollector.cpp.s:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/AbstractCollector.cpp.s
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/AbstractCollector.cpp.s
.PHONY : src/AbstractCollector.cpp.s

src/SSHCollector.o: src/SSHCollector.cpp.o

.PHONY : src/SSHCollector.o

# target to build an object file
src/SSHCollector.cpp.o:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/SSHCollector.cpp.o
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/SSHCollector.cpp.o
.PHONY : src/SSHCollector.cpp.o

src/SSHCollector.i: src/SSHCollector.cpp.i

.PHONY : src/SSHCollector.i

# target to preprocess a source file
src/SSHCollector.cpp.i:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/SSHCollector.cpp.i
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/SSHCollector.cpp.i
.PHONY : src/SSHCollector.cpp.i

src/SSHCollector.s: src/SSHCollector.cpp.s

.PHONY : src/SSHCollector.s

# target to generate assembly for a file
src/SSHCollector.cpp.s:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/SSHCollector.cpp.s
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/SSHCollector.cpp.s
.PHONY : src/SSHCollector.cpp.s

src/SSHsCollector.o: src/SSHsCollector.cpp.o

.PHONY : src/SSHsCollector.o

# target to build an object file
src/SSHsCollector.cpp.o:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/SSHsCollector.cpp.o
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/SSHsCollector.cpp.o
.PHONY : src/SSHsCollector.cpp.o

src/SSHsCollector.i: src/SSHsCollector.cpp.i

.PHONY : src/SSHsCollector.i

# target to preprocess a source file
src/SSHsCollector.cpp.i:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/SSHsCollector.cpp.i
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/SSHsCollector.cpp.i
.PHONY : src/SSHsCollector.cpp.i

src/SSHsCollector.s: src/SSHsCollector.cpp.s

.PHONY : src/SSHsCollector.s

# target to generate assembly for a file
src/SSHsCollector.cpp.s:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/src/SSHsCollector.cpp.s
	$(MAKE) -f CMakeFiles/SSHCollector.dir/build.make CMakeFiles/SSHCollector.dir/src/SSHsCollector.cpp.s
.PHONY : src/SSHsCollector.cpp.s

test/SSHCollectorTestCases.o: test/SSHCollectorTestCases.cpp.o

.PHONY : test/SSHCollectorTestCases.o

# target to build an object file
test/SSHCollectorTestCases.cpp.o:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/test/SSHCollectorTestCases.cpp.o
.PHONY : test/SSHCollectorTestCases.cpp.o

test/SSHCollectorTestCases.i: test/SSHCollectorTestCases.cpp.i

.PHONY : test/SSHCollectorTestCases.i

# target to preprocess a source file
test/SSHCollectorTestCases.cpp.i:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/test/SSHCollectorTestCases.cpp.i
.PHONY : test/SSHCollectorTestCases.cpp.i

test/SSHCollectorTestCases.s: test/SSHCollectorTestCases.cpp.s

.PHONY : test/SSHCollectorTestCases.s

# target to generate assembly for a file
test/SSHCollectorTestCases.cpp.s:
	$(MAKE) -f CMakeFiles/SSHCollectorTestCases.dir/build.make CMakeFiles/SSHCollectorTestCases.dir/test/SSHCollectorTestCases.cpp.s
.PHONY : test/SSHCollectorTestCases.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... SSHCollectorTestCases"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SSHCollector"
	@echo "... src/AbstractCollector.o"
	@echo "... src/AbstractCollector.i"
	@echo "... src/AbstractCollector.s"
	@echo "... src/SSHCollector.o"
	@echo "... src/SSHCollector.i"
	@echo "... src/SSHCollector.s"
	@echo "... src/SSHsCollector.o"
	@echo "... src/SSHsCollector.i"
	@echo "... src/SSHsCollector.s"
	@echo "... test/SSHCollectorTestCases.o"
	@echo "... test/SSHCollectorTestCases.i"
	@echo "... test/SSHCollectorTestCases.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

